debug: false
management.endpoints.web.exposure.include: "*"

# 서버 재기동 없이 Thymeleaf 수정시 바로 reload 됨.
# 아래와 같이 prefix로 위치 설정은 해줘야한다. 이유는 default 위치가 /templates/로 되어 있기때무이다.
# 그리고 cache 와 livereload.enable 설정을 따로 해주지 않아도 되나,
# 이런 설정도 추가로 할수 있다라는 점을 참고하자.
# 단, 운영에는 주석처리한 부분을 적용하면 안된다. 이유는 서버에 무리를 줄수 있다.
#spring.thymeleaf.cache: false
spring.thymeleaf.prefix: file:src/main/resources/templates/
#spring.devtools.livereload.enabled: true #default

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: uno
    password: uno01
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    # resources/data.sql 사용하기위해 사용됨.
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show_sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.use_sql_comments: true
      hibernate:
        show_sql: true
#  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true





logging:
  level:
    com.example.projectboard: debug
    #request, response ??? ??
    org.springframework.web.servlet: debug
    #jpa ?? ??
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        #springboot 3.0 이상부터 logging.level.org.hibernate.orm.jdbc.bind: trace 로 해야 jpa 쿼리 parameter 로그 확인 가능
        orm:
          jdbc:
            bind: trace

---

spring:
  config.activate.on-profile: testdb


